dist:
  module: github.com/wieso/zabbixreceiver/examples/ocb/otelcol-zabbix
  name: otelcol-zabbix
  description: OpenTelemetry Collector with the Zabbix receiver
  output_path: ./otelcol-zabbix-dist
  version: 0.3.1

receivers:
  - gomod: github.com/wieso/zabbixreceiver/receiver/zabbixreceiver v0.3.1

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.160.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.160.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.66.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.66.0

telemetry:
  gomod: go.opentelemetry.io/collector/service v0.160.0
  import: go.opentelemetry.io/collector/service/telemetry/otelconftelemetry
